version: '3.9'
services:
  db:
    env_file:
      - .env
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - prod-db:/var/lib/postgresql/data
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
volumes:
  prod-db:
    driver: local
