version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.test
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local